version: '2'
services:
  data:
    image: busybox
    command: /bin/sh
    volumes:
      - /share
      - ..:/app
      - ./nginx_dev/app.conf:/etc/nginx/conf.d/app.conf
      # - ./mysql/app.conf:/etc/mysql/conf.d/app.conf:ro
  db:
    env_file: ../.env
    image: mdillon/postgis
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      PGDATA: /app/db/postgres/data
    volumes_from:
      - data
  # mysql:
  #   env_file: ../.env
  #   image: mysql
  #   environment:
  #     MYSQL_DATABASE: $MYSQL_DATABASE
  #     MYSQL_USER: $MYSQL_USER
  #     MYSQL_PASSWORD: $MYSQL_PASSWORD
  #     MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
  #     PGDATA: /app/db/mysql/data
  #   volumes_from:
  #     - data
  nginx_dev:
    image: nginx
    ports:
     - "80:80"
    volumes_from:
      - data
  rails:
    build:
      context: ../
      dockerfile: docker/rails/Dockerfile
    env_file: ../.env
    volumes_from:
      - data
    ports:
     - $RAILS_PORT:$RAILS_PORT
  front:
    build:
      context: ../
      dockerfile: docker/front/Dockerfile
    env_file: ../.env
    volumes_from:
      - data
    ports:
     - $NODE_PORT:$NODE_PORT
