version: '2'
services:
  data:
    image: busybox
    command: /bin/sh
    volumes:
      - /share
      - ..:/app
    user: ${USER_ID}:${GROUP_ID}
  db:
    image: mdillon/postgis
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    volumes:
      - ../tmp/db:/var/lib/postgresql/data
  nginx:
    build:
      context: ../
      dockerfile: docker/nginx/Dockerfile
    depends_on: 
      - rails
      - front
    ports:
     - "80:${WEB_PORT}"
     - "${WEB_PORT}:${WEB_PORT}"
    environment:
      - PORT=$WEB_PORT
      - RAILS_PORT
      - NODE_PORT
      - NODE_ENV=development
    volumes_from:
      - data
  rails:
    build:
      context: ../
      dockerfile: docker/rails/Dockerfile
      args:
        - RUBY_VERSION
        - USER_ID
        - GROUP_ID
    working_dir: /app
    depends_on:
      - db
    ports:
      - $RAILS_PORT:$RAILS_PORT
    volumes_from:
      - data
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    environment:
      - PORT=$RAILS_PORT
      - RAILS_ENV=development
      - SECRET_KEY_BASE
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
    user: ${USER_ID}:${GROUP_ID}
    ports:
     - $RAILS_PORT:$RAILS_PORT
  front:
    build:
      context: ../
      dockerfile: docker/front/Dockerfile
    volumes_from:
      - data
    volumes:
      - /etc/group:/etc/group:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/shadow:/etc/shadow:ro
    ports:
     - $NODE_PORT:$NODE_PORT
    environment:
      - NODE_ENV=development
