export default {
  "ファストフード":{id:4, importance: 1},
  "マクドナルド":{id:10, parentId:4, image:"//oasis.mogya.com/images/design/spot_icon_01_[type]_[size]px.png", importance: 5},
  "モスバーガー":{id:12, parentId:4, image:"//oasis.mogya.com/images/design/spot_icon_02_[type]_[size]px.png", importance: 5},
  "ロッテリア":{id:13, parentId:4, image:"//oasis.mogya.com/images/design/spot_icon_03_[type]_[size]px.png", importance: 5},
  "ケンタッキーフライドチキン":{id:16, parentId:4, image:"//oasis.mogya.com/images/design/spot_icon_04_[type]_[size]px.png", importance: 5},
  "ミスタードーナツ":{id:11, parentId:4, image:"//oasis.mogya.com/images/design/spot_icon_05_[type]_[size]px.png", importance: 5},
  "クリスピークリームドーナツ":{id:76, parentId:4, image:"//oasis.mogya.com/images/design/spot_icon_06_[type]_[size]px.png", importance: 5},
  "サブウェイ":{id:17, parentId:4, image:"//oasis.mogya.com/images/design/spot_icon_06_[type]_[size]px.png", importance: 5},
  "バーガーキング":{id:14, parentId:4, image:"//oasis.mogya.com/images/design/spot_icon_06_[type]_[size]px.png", importance: 5},
  "ウェンディーズ":{id:15, parentId:4, image:"//oasis.mogya.com/images/design/spot_icon_06_[type]_[size]px.png", importance: 5},
  "ファーストキッチン":{id:20, parentId:4, image:"//oasis.mogya.com/images/design/spot_icon_06_[type]_[size]px.png", importance: 5},
  "フレッシュネスバーガー":{id:19, parentId:4, image:"//oasis.mogya.com/images/design/spot_icon_06_[type]_[size]px.png", importance: 5},
  "ファストフード(その他)":{id:54, parentId:4, image:"//oasis.mogya.com/images/design/spot_icon_06_[type]_[size]px.png", importance: 5},
  "喫茶店":{id:6, importance: 1},
  "銀座ルノアール":{id:21, parentId:6, image:"//oasis.mogya.com/images/design/spot_icon_07_[type]_[size]px.png", importance: 5},
  "サンマルクカフェ":{id:98, parentId:6, image:"//oasis.mogya.com/images/design/spot_icon_25_[type]_[size]px.png", importance: 5},
  "スターバックス":{id:24, parentId:6, image:"//oasis.mogya.com/images/design/spot_icon_08_[type]_[size]px.png", importance: 5},
  "カフェ・ド・クリエ":{id:48, parentId:6, image:"//oasis.mogya.com/images/design/spot_icon_09_[type]_[size]px.png", importance: 5},
  "シアトルズベスト":{id:49, parentId:6, image:"//oasis.mogya.com/images/design/spot_icon_10_[type]_[size]px.png", importance: 5},
  "タリーズコーヒー":{id:23, parentId:6, image:"//oasis.mogya.com/images/design/spot_icon_11_[type]_[size]px.png", importance: 5},
  "ドトール/エクセルシオール":{id:22, parentId:6, image:"//oasis.mogya.com/images/design/spot_icon_12_[type]_[size]px.png", importance: 5},
  "プロント":{id:47, parentId:6, image:"//oasis.mogya.com/images/design/spot_icon_13_[type]_[size]px.png", importance: 5},
  "シャノアール（ベローチェ）":{id:26, parentId:6, image:"//oasis.mogya.com/images/design/spot_icon_14_[type]_[size]px.png", importance: 5},
  "珈琲館":{id:46, parentId:6, image:"//oasis.mogya.com/images/design/spot_icon_15_[type]_[size]px.png", importance: 5},
  "上島珈琲店":{id:59, parentId:6, image:"//oasis.mogya.com/images/design/spot_icon_16_[type]_[size]px.png", importance: 5},
  "喫茶店(その他)":{id:53, parentId:6, image:"//oasis.mogya.com/images/design/spot_icon_17_[type]_[size]px.png", importance: 3},
  "ネットカフェ":{id:7, image:"//oasis.mogya.com/images/design/spot_icon_18_[type]_[size]px.png", importance: 1},
  "メディアカフェポパイ":{id:40, parentId:7, image:"//oasis.mogya.com/images/design/spot_icon_18_[type]_[size]px.png", importance: 5},
  "アプレシオ":{id:30, parentId:7, image:"//oasis.mogya.com/images/design/spot_icon_18_[type]_[size]px.png", importance: 5},
  "ほっとステーション":{id:41, parentId:7, image:"//oasis.mogya.com/images/design/spot_icon_18_[type]_[size]px.png", importance: 5},
  "まんがランド":{id:37, parentId:7, image:"//oasis.mogya.com/images/design/spot_icon_18_[type]_[size]px.png", importance: 5},
  "まんが広場":{id:36, parentId:7, image:"//oasis.mogya.com/images/design/spot_icon_18_[type]_[size]px.png", importance: 5},
  "ゆう遊空間":{id:28, parentId:7, image:"//oasis.mogya.com/images/design/spot_icon_18_[type]_[size]px.png", importance: 5},
  "らくだ":{id:34, parentId:7, image:"//oasis.mogya.com/images/design/spot_icon_18_[type]_[size]px.png", importance: 5},
  "アイ・カフェ":{id:35, parentId:7, image:"//oasis.mogya.com/images/design/spot_icon_18_[type]_[size]px.png", importance: 5},
  "エアーズカフェ":{id:33, parentId:7, image:"//oasis.mogya.com/images/design/spot_icon_18_[type]_[size]px.png", importance: 5},
  "ゲオカフェ":{id:44, parentId:7, image:"//oasis.mogya.com/images/design/spot_icon_18_[type]_[size]px.png", importance: 5},
  "ゲラゲラ":{id:27, parentId:7, image:"//oasis.mogya.com/images/design/spot_icon_18_[type]_[size]px.png", importance: 5},
  "コミックバスター":{id:39, parentId:7, image:"//oasis.mogya.com/images/design/spot_icon_18_[type]_[size]px.png", importance: 5},
  "サイバック":{id:43, parentId:7, image:"//oasis.mogya.com/images/design/spot_icon_18_[type]_[size]px.png", importance: 5},
  "スペースクリエイト自遊空間":{id:31, parentId:7, image:"//oasis.mogya.com/images/design/spot_icon_18_[type]_[size]px.png", importance: 5},
  "バグース":{id:38, parentId:7, image:"//oasis.mogya.com/images/design/spot_icon_18_[type]_[size]px.png", importance: 5},
  "マンボー":{id:29, parentId:7, image:"//oasis.mogya.com/images/design/spot_icon_18_[type]_[size]px.png", importance: 5},
  "快活CLUB":{id:32, parentId:7, image:"//oasis.mogya.com/images/design/spot_icon_18_[type]_[size]px.png", importance: 5},
  "ワイプ":{id:67, parentId:7, image:"//oasis.mogya.com/images/design/spot_icon_18_[type]_[size]px.png", importance: 5},
  "ネットカフェ(その他)":{id:52, parentId:7, image:"//oasis.mogya.com/images/design/spot_icon_18_[type]_[size]px.png", importance: 5},
  "飲食店":{id:64, image:"//oasis.mogya.com/images/design/spot_icon_19_[type]_[size]px.png", importance: 1},
  "ココイチ":{id:116, parentId:64, importance: 5},
  "バー":{id:66, parentId:64, image:"//oasis.mogya.com/images/design/spot_icon_19_[type]_[size]px.png", importance: 5},
  "ファミレス":{id:109, parentId:64, importance: 5},
  "フードコート":{id:118, parentId:64, importance: 5},
  "飲食店(その他)":{id:65, parentId:64, image:"//oasis.mogya.com/images/design/spot_icon_19_[type]_[size]px.png", importance: 5},
  "居酒屋":{id:75, parentId:64, image:"//oasis.mogya.com/images/design/spot_icon_19_[type]_[size]px.png", importance: 5},
  "レンタルオフィス":{id:9, image:"//oasis.mogya.com/images/design/spot_icon_20_[type]_[size]px.png", importance: 1},
  "デスカット":{id:45, parentId:9, importance: 5},
  "その他レンタルオフィス":{id:56, parentId:9, image:"//oasis.mogya.com/images/design/spot_icon_20_[type]_[size]px.png", importance: 5},
  "その他":{id:55, image:"//oasis.mogya.com/images/design/spot_icon_23_[type]_[size]px.png", importance: 0},
  "てもみん":{id:100, parentId:55, image:"//oasis.mogya.com/images/design/spot_icon_31_[type]_[size]px.png", importance: 5},
  "イートインスペース":{id:99, parentId:55, importance: 5},
  "カラオケ":{id:72, parentId:55, image:"//oasis.mogya.com/images/design/spot_icon_21_[type]_[size]px.png", importance: 5},
  "カーディーラー":{id:106, parentId:55, importance: 5},
  "カー用品店":{id:105, parentId:55, importance: 5},
  "コワーキングスペース":{id:97, parentId:55, image:"//oasis.mogya.com/images/design/spot_icon_26_[type]_[size]px.png", importance: 5},
  "コンビニエンスストア":{id:60, parentId:55, image:"//oasis.mogya.com/images/design/spot_icon_30_[type]_[size]px.png", importance: 1},
  "セブンイレブン":{id:104, parentId:60, image:"//oasis.mogya.com/images/design/spot_icon_28_[type]_[size]px.png", importance: 5},
  "ファミリーマート":{id:102, parentId:60, image:"//oasis.mogya.com/images/design/spot_icon_29_[type]_[size]px.png", importance: 5},
  "ローソン":{id:103, parentId:60, image:"//oasis.mogya.com/images/design/spot_icon_27_[type]_[size]px.png", importance: 5},
  "ネイルサロン":{id:101, parentId:55, image:"//oasis.mogya.com/images/design/spot_icon_32_[type]_[size]px.png", importance: 5},
  "フィットネスクラブ":{id:107, parentId:55, importance: 5},
  "ホテル":{id:93, parentId:55, image:"//oasis.mogya.com/images/design/spot_icon_23_[type]_[size]px.png", importance: 5},
  "メイドカフェなど(萌)":{id:63, parentId:55, image:"//oasis.mogya.com/images/design/spot_icon_22_[type]_[size]px.png", importance: 5},
  "献血ルーム":{id:94, parentId:55, image:"//oasis.mogya.com/images/design/spot_icon_23_[type]_[size]px.png", importance: 5},
  "理髪店・美容院":{id:96, parentId:55, image:"//oasis.mogya.com/images/design/spot_icon_33_[type]_[size]px.png", importance: 5},
  "公共施設":{id:69, parentId:55, image:"//oasis.mogya.com/images/design/spot_icon_23_[type]_[size]px.png", importance: 1},
  "待合室・ラウンジ":{id:61, parentId:55, image:"//oasis.mogya.com/images/design/spot_icon_23_[type]_[size]px.png", importance: 5},
  "図書館":{id:8, parentId:55, image:"//oasis.mogya.com/images/design/spot_icon_24_[type]_[size]px.png", importance: 5},
  "百貨店":{id:108, parentId:55, image:"//oasis.mogya.com/images/design/spot_icon_34_[type]_[size]px.png", importance: 5}
};
