export default {
  "電源OK": {pos:0, text:'電源:OK'},
  "電源NG": {pos:1, text:'電源:NG'},
  "電源:実績あり": {pos:2, text:'使えた<br />実績あり'},
  "電源あり(喫煙席)": {pos:3, text:'電源あり<br />(喫煙席)'},
  "電源あり(禁煙席)": {pos:4, text:'電源あり(禁煙席)'},
  "Qi": {pos:9, text:'ワイヤレス<br />充電'},
  "タバコ:全席禁煙": {pos:6, text:'全席禁煙'},
  "タバコ:全席喫煙可": {pos:7, text:'全席喫煙'},
  "タバコ:分煙": {pos:8, text:'分煙'},
  "イートインスペース": {pos:24, text:'イートイン<br />スペース'},
  "電源:お客様用コンセント": {pos:0, text:'お客様用<br />コンセント'},
  "電源:壁コンセント": {pos:2, text:'壁コンセント'},
  "電源:USB": {pos:27, text:'USB<br />コンセント'},

  "ソフトバンクWi-Fi": {pos:10, text:'Softbank<br />Wi-Fi'},
  "docomo Wi-Fi": {pos:11, text:'ドコモ<br />Wi-Fi'},
  "au Wi-Fi": {pos:12, text:'au Wi-Fi'},
  "フレッツ・スポット": {pos:15, text:'フレッツ<br />スポット'},
  "BBモバイルポイント": {pos:16, text:'BBモバイル<br />ポイント'},
  "FREESPOT": {pos:17, text:'FREESPOT'},
  "有線LAN": {pos:18, text:'有線LAN'},
  "独自": {pos:19, text:'独自'},
  "wi2": {pos:25, text:'wi2'},
  "Tullys Wi-Fi": {pos:26, text:"Tullys<br />Wi-Fi"},
  "Other Wi-Fi": {pos:19, text:"その他"},
};
